description: Build a Docker image

parameters:

  image-name:
    type: string
    description: Name of the Docker image (e.g., youruser/chat-client)

  tag:
    type: string
    default: latest
    description: Tag of the image (e.g., latest, build-123)

  dockerfile-path:
    type: string
    default: Dockerfile
    description: Path to Dockerfile (e.g., ./client/Dockerfile)

  build-context:
    type: string
    default: .
    description: Build context path (e.g., ./client)

  build-args:
    type: steps
    default: []
    description: |
      Optional build arguments as a list (e.g., ["NODE_ENV=production", "API_URL=https://api.example.com"])

steps:

  - run:
      name: Show Docker Version
      command: docker --version

  - run:
      name: Build Docker Image
      command: |
        echo "📦 Building Docker image << parameters.image-name >>:<< parameters.tag >>"
        echo "Using Dockerfile at << parameters.dockerfile-path >>"
        
        BUILD_ARGS=""
        <<# parameters.build-args >>
        BUILD_ARGS="$BUILD_ARGS --build-arg << parameters.build-args >>"
        echo "➡️ Adding build arg: << parameters.build-args >>"
        <</ parameters.build-args >>
        
        if [ -n "$BUILD_ARGS" ]; then
          echo "🔧 Building with build arguments"
          docker build -t "<< parameters.image-name >>:<< parameters.tag >>" \
            -f "<< parameters.dockerfile-path >>" \
            $BUILD_ARGS \
            "<< parameters.build-context >>"
        else
          echo "🔧 Building without build arguments"
          docker build -t "<< parameters.image-name >>:<< parameters.tag >>" \
            -f "<< parameters.dockerfile-path >>" \
            "<< parameters.build-context >>"
        fi
        